### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by hbujhkl** [ropensci/tabulizer#35] opened 2017-02-07 21:27 UTC
I am encountering a Java error when I try to use tabulizer. Here is the relevant code and the error:

![sg](https://cloud.githubusercontent.com/assets/25621920/22712190/bd062108-ed38-11e6-8ffc-2c4b51ded50e.jpg)

The options command maxes out the memory available to Java. 

I'm working on a MacBook Pro (Retina, 13-inch, Mid 2014), 2.8 GHz Intel Core i5, 16 GB 1600 MHz DDR3
R 3.3.2

**Comment by leeper** [comment] 2017-02-09 09:05
Duplicate of #19

**Closed by leeper** 2017-02-09 09:05 UTC
Labels: question
